[package]
name = "subtraction"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
ndarray-stats = "0.6.0"
dbgbb = { version="0.3.2", features=["ndarray_16"] }
bulletin-board-client = { version="0.3.3", features=["ndarray_16"] }
special-fun = "0.3.0"